<?php

namespace App\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
	public function show_activity() {
        $dql = 'SELECT a.id, a.user, u.username, a.lastActivity, a.userAgent, a.ip, a.lastPage
            FROM AppUserBundle:Activity a
            INNER JOIN AppUserBundle:User u
            WHERE a.user = u.id
            ORDER BY a.lastActivity DESC';

        $query = $this->getEntityManager()->createQuery($dql);

        $result = $query->execute();
        return $result;
	}

    public function show_user_activity($user) {
        $dql = 'SELECT a.lastActivity
            FROM AppUserBundle:Activity a
            INNER JOIN AppUserBundle:User u
            WHERE a.user = u.id
            WHERE a.user = :user';

        $query = $this->getEntityManager()->createQuery($dql)
                      ->SetParameter('user', $user);

        $result = $query->execute();

        if(empty($result))
            return 'неизвестно';
        else
            return $result[0]['lastActivity'];
    }    
}