<?php

namespace App\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function show_all_users($page, $sort)
    {

        if($sort == 'alpha_asc')
            $orber_by = "username ASC";
        else if ($sort == 'alpha_desc')
            $orber_by = "username DESC";
        else if ($sort == 'since_asc')
            $orber_by = "id ASC";
        else if ($sort == 'since_desc')
            $orber_by = "id DESC";

        $dql = 'SELECT u.id, u.username, u.email, u.image, n.number, u.created
            FROM AppUserBundle:User u
            LEFT JOIN AppGuestbookBundle:Number n
            WHERE u.id = n.user
            WHERE u.enabled = 1
            ORDER BY u.'.$orber_by;

        $query = $this->getEntityManager()->createQuery($dql);

        $result = $query->execute();
        return $result;
    }       

	public function show_roles() {
        $dql = 'SELECT u.id, u.roles
            FROM AppUserBundle:User u';

        $query = $this->getEntityManager()->createQuery($dql);

        $result = $query->execute();

        $roles = [];

        for($i=0;$i<count($result);$i++) {
        	$id = $result[$i]['id'];
        	$ban = $result[$i]['roles'][1];

        	$roles[$id] = $ban;
        }

        return $roles;
	}

    public function get_users() {
        $dql = "SELECT u.id, u.username FROM AppUserBundle:User u ORDER BY u.username ASC";

        $query = $this->getEntityManager()->createQuery($dql);
        $result = $query->execute();

        $results = [];
        for($i=0;$i<count($result);$i++) {
            $id = $result[$i]['id'];
            $username = $result[$i]['username'];
            $results[$username] = $id;
        }
        return $results;
    }

    public function get_admins($assistant) {

        $dql = "SELECT u.id, u.username, u.roles FROM AppUserBundle:User u ORDER BY u.username ASC";

        $query = $this->getEntityManager()->createQuery($dql);
        $result = $query->execute();

        $results = [];
        $admins_role = ['ROLE_MODERATE', 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN'];
        for($i=0;$i<count($result);$i++) {
            $id = $result[$i]['id'];
            $username = $result[$i]['username'];
            $roles = $result[$i]['roles'];

            if(!in_array('ROLE_VERIFIED_USER', $roles)) {
                if(in_array($id, $assistant))
                    $access = 1;
                else
                    $access = 0;

                $results[] = ['id' => $id, 'username' => $username, 'access' => $access];
            }
        }
        return $results;
    }
}