<?php

namespace App\TournamentBundle\Repository;

/**
 * BonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonusRepository extends \Doctrine\ORM\EntityRepository
{
}
