<?php

namespace App\TournamentBundle\Repository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
	public function get_content($page)
	{
        $dql = 'SELECT c.title, c.chapter, c.description
            FROM AppTournamentBundle:Content c
            WHERE c.chapter = :chapter
            ORDER BY c.id DESC';

        $query = $this->getEntityManager()->createQuery($dql)
                ->SetParameter('chapter', $page)
                ->SetMaxResults(1);

        $result = $query->execute();

        if(empty($result))
            return 0;
        else
            return $result[0];
	}
}
