<?php

namespace App\TournamentBundle\Repository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
	public function get_content($page)
	{
        $dql = 'SELECT c.description
            FROM AppTournamentBundle:Content c
            WHERE c.title = :title
            ORDER BY c.id DESC';

        $query = $this->getEntityManager()->createQuery($dql)
                ->SetParameter('title', $page)
                ->SetMaxResults(1);

        $result = $query->execute();
        return $result;
	}
}
