<?php

namespace App\TournamentBundle\Repository;

/**
 * ForescoredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForescoredRepository extends \Doctrine\ORM\EntityRepository
{
}
