<?php

namespace App\TournamentBundle\Repository;

/**
 * ForecastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastRepository extends \Doctrine\ORM\EntityRepository
{
	public function get_forecast($forebridge) {

		$dql = "SELECT f FROM AppTournamentBundle:Forecast f WHERE f.hash = :hash";

		$query = $this->getEntityManager()->createQuery($dql)
			 ->SetParameter('hash', $forebridge);

		$result = $query->execute();

		if(empty($result))
			$result = 0;

		return $result;
	}
}
