<?php

namespace App\TournamentBundle\Repository;

/**
 * ForecastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastRepository extends \Doctrine\ORM\EntityRepository
{
	public function how_games($hash) {
		$dql = "SELECT count(f.id) as summ FROM AppTournamentBundle:Forecast f WHERE f.hash = :hash";

		$query = $this->getEntityManager()->createQuery($dql)
			 ->SetParameter('hash', $hash);

		$result = $query->execute();

		if(empty($result))
			return 0;
		else
			return $result[0]['summ'];
	}

	public function get_forecast($forebridge) {

		$dql = "SELECT f FROM AppTournamentBundle:Forecast f WHERE f.hash = :hash";

		$query = $this->getEntityManager()->createQuery($dql)
			 ->SetParameter('hash', $forebridge);

		$result = $query->execute();

		if(empty($result))
			$result = 0;

		return $result;
	}

	public function getActiveTours($types) {

		$date = date('Y-m-d H:i');

		$dql = "SELECT t.name, b.tour, f.hash, f.team1, f.team2 
				FROM AppTournamentBundle:Forecast f
				INNER JOIN AppTournamentBundle:Forebridge b
				WHERE f.hash = b.hash
				INNER JOIN AppTournamentBundle:Tournament t
				WHERE b.tr = t.id
				WHERE f.timer > :nowdate AND t.types = :types";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter('nowdate', $date)
					  ->SetParameter('types', $types);

		$result = $query->execute();

		if(empty($result)) {
			$results = 0;
		} else {
			$results = [];
			for($i=0;$i<count($result);$i++) {
				$hash = $result[$i]['hash'];
				$team1 = $result[$i]['team1'];
				$team2 = $result[$i]['team2'];
				$name = $result[$i]['name'];
				$tour = $result[$i]['tour'];

				$results[$hash][] = ["team1" => $team1, "team2" => $team2, "hash" => $hash, "tr" => $name,
									 "tour" => $tour];
			}
		}

		return $results;
	}

	public function get_cast_info($idfore) {

		$dql = "SELECT f.timer FROM AppTournamentBundle:Forecast f
				WHERE f.id = :id";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("id", $idfore);

		$result = $query->execute();

		return $result;
	}

	public function is_exist($tr, $tour) {

		$dql = "SELECT f.id FROM AppTournamentBundle:Forebridge f
				WHERE f.tr = :tr AND f.tour = :tour";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("tr", $tr)
					  ->SetParameter("tour", $tour);

		$result = $query->execute();

		if(empty($result))
			return 0;
		else
			return 1;
	}

	public function get_scored_info($forebridge) {
		$dql = "SELECT f.timer FROM AppTournamentBundle:Forecast f
				WHERE f.hash = :hash";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("hash", $forebridge);

		$result = $query->execute();

		return $result;
	}

	public function get_tour_status($tr, $tour) {
		$dql = "SELECT f.hash FROM AppTournamentBundle:Forebridge f
				WHERE f.tr = :tr AND f.tour = :tour";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("tr", $tr)
					  ->SetParameter("tour", $tour)
					  ->SetMaxResults(1);

		$result = $query->execute();

		if(empty($result)) {
			$status = 0;
		} else {

			$dql = "SELECT f.id FROM AppTournamentBundle:Forecast f
					WHERE f.hash = :hash AND f.result1 is null";

			$query = $this->getEntityManager()->createQuery($dql)
						  ->SetParameter("hash", $result[0]['hash'])
						  ->SetMaxResults(1);

			$null = $query->execute();			

			if(!empty($null))
				$status = 1;
			else
				$status = 2;

		}

		return $status;

	}	

	public function getTimeTour($forebridge)
	{

		if(!$forebridge)
			return 0;

		$dql = "SELECT min(f.timer) FROM AppTournamentBundle:Forecast f
				WHERE f.hash = :hash";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("hash", $forebridge);

		$result = $query->execute();

		if($result)
			$time = $result[0][1];
		else
			$time = 0;

		return $time;
	}

	public function getGames($forebridge)
	{
		$dql = "SELECT f.team1, f.team2, f.id FROM AppTournamentBundle:Forecast f
				WHERE f.hash = :hash";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("hash", $forebridge);

		$result = $query->execute();

		$games = [];
		foreach ($result as $k => $v){
			$t = $v['team1']." - ".$v['team2'];
			$i = $v['id'];
			$games[$t] = $i;
		}

		return $games;
	}

	public function getAccuracy($forebridge, $user)
	{
		$dql = "SELECT count(f) FROM AppTournamentBundle:Forecast f
				INNER JOIN AppTournamentBundle:Usercast u
				WHERE u.idfore = f.id AND (f.result1 = u.result1 AND f.result2 = u.result2)
				WHERE f.hash = :hash AND f.added is null AND u.user = :user";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("hash", $forebridge)
					  ->SetParameter("user", $user);

		$result = $query->execute();

		return $result[0][1];
	}

}
