<?php

namespace App\TournamentBundle\Repository;

/**
 * HeadteamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadteamRepository extends \Doctrine\ORM\EntityRepository
{

	public function showHeadTeam($team) {
		$dql = "SELECT h.id FROM AppTournamentBundle:Headteam h
				WHERE h.name = :team";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("team", $team);

		$result = $query->execute();

		if(empty($result))
			return 0;
		else
			return 1;
	}

	public function get_teams() {
		$dql = "SELECT h.id, h.name FROM AppTournamentBundle:Headteam h
				ORDER BY h.name ASC";

		$query = $this->getEntityManager()->createQuery($dql);

		$result = $query->execute();

		return $result;
	}

	public function get_team($team) {
		$dql = "SELECT h.id, h.name FROM AppTournamentBundle:Headteam h
				WHERE h.id = :team";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter('team', $team);

		$result = $query->execute();

		$info = [];
		if(!empty($result)) {
			$info['name'] = $result[0]['name'];
			$info['id'] = $result[0]['id'];
		} else {
			$info['name'] = '';
			$info['id'] = 0;
		}

		return $info;
	}

}
