<?php

namespace App\TournamentBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
	public function get_players($team) {
		$dql = "SELECT p FROM AppTournamentBundle:Player p
				WHERE p.team = :team AND p.status = 1
				ORDER BY p.position ASC, p.second ASC";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter('team', $team);

		$result = $query->execute();

		return $result;	
	}

	public function show_player($playerid) {
		$dql = "SELECT p.id, p.first, p.second, p.position, p.status FROM AppTournamentBundle:Player p
				WHERE p.id = :player";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter('player', $playerid);

		$result = $query->execute();

		if(empty($result)) {
			return 0;
		} else {
			$player = [];
			$player['id'] = $result[0]['id'];
			$player['first'] = $result[0]['first'];
			$player['second'] = $result[0]['second'];
			$player['position'] = $result[0]['position'];
			$player['status'] = $result[0]['status'];

			return $player;	
		}

	}

	public function get_position($player) {
		$dql = "SELECT p.position FROM AppTournamentBundle:Player p
				WHERE p.id = :player";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter('player', $player);

		$result = $query->execute();

		return $result[0]['position'];
	}
}
