<?php

namespace App\TournamentBundle\Repository;

/**
 * TablelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablelistRepository extends \Doctrine\ORM\EntityRepository
{
	public function show_table($tr, $tour) {
		$dql = "SELECT sum(t.game), sum(t.w), sum(t.n), sum(t.l), sum(t.bw), sum(t.bl), sum(t.score) FROM AppTournamentBundle:Tablelist t
			INNER JOIN AppUserBundle:User u
			WHERE u.id = t.user
			WHERE t.tr = :tr AND t.tour <= :tour";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("tr", $tr)
					  ->SetParameter("tour", $tour);

		$result = $query->execute();

		return $result;
	}

}
