<?php

namespace App\TournamentBundle\Repository;

/**
 * TablelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablelistRepository extends \Doctrine\ORM\EntityRepository
{
	public function show_table($tr, $tour) {
		$dql = "SELECT t.user, u.username, u.image, sum(t.game) as game, sum(t.w) as w, sum(t.n) as n, sum(t.l) as l, sum(t.bw) as bw, sum(t.bl) as bl, sum(t.score) as score FROM 	  	AppTournamentBundle:Tablelist t
			INNER JOIN AppUserBundle:User u
			WHERE u.id = t.user
			WHERE t.tr = :tr AND t.tour <= :tour
			GROUP BY t.user
			ORDER BY score DESC, bw DESC, bl DESC, u.username ASC";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter("tr", $tr)
					  ->SetParameter("tour", $tour);

		$result = $query->execute();

		return $result;
	}

}
