<?php

namespace App\TournamentBundle\Repository;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRepository extends \Doctrine\ORM\EntityRepository
{

	public function show_tournaments_list($page) {
	    $list = $page - 1;
	    $how = 10;
	    if($list > 0)
	        $list = $list * $how;

		$dql = "SELECT t.id, t.name, t.image, t.status
				FROM AppTournamentBundle:Tournament t
				WHERE t.status != 0 AND t.status != 2
				ORDER BY t.id DESC";

		$query = $this->getEntityManager()->createQuery($dql);

		$tournament = $query->execute();

	    $dql = 'SELECT count(t) FROM AppTournamentBundle:Tournament t';
	    
	    $query = $this->getEntityManager()->createQuery($dql);

	    $rowcount = $query->execute();
	    $count = ceil($rowcount[0][1]/$how);

		return array($tournament, $count);

	}

	public function show_tournament_for_admin($tournament) {
		$dql = "SELECT t.id, t.types, t.name, t.access, t.image, t.info, t.status FROM AppTournamentBundle:Tournament t
			WHERE t.id = :id";

		$query = $this->getEntityManager()->createQuery($dql)
					->SetParameter("id", $tournament);

		$result = $query->execute();

		if(!empty($result)) {
			$result = $result[0];

			$result['info'] = unserialize($result['info']);
			$result['access'] = unserialize($result['access']);
		}

		return $result;
	}

}
