<?php

namespace App\TournamentBundle\Repository;

/**
 * UsercastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsercastRepository extends \Doctrine\ORM\EntityRepository
{
}
