services:
    twig.extension.mode_numbers:
        class: App\GuestbookBundle\Twig\ModeNumberExtension
        public: true
        tags:
          - { name: twig.extension }  
#    app_guestbook.example:
#        class: App\GuestbookBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
