<?php

namespace App\AdminBundle\Repository;

use App\GuestbookBundle\Repository\GuestbookRepository;

/**
 * AdminbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminbookRepository extends GuestbookRepository {

    protected $bundle = "AppAdminBundle:Adminbook";

}
