<?php

namespace App\GuestbookBundle\Repository;

/**
 * ChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionRepository extends \Doctrine\ORM\EntityRepository
{
	public function get_champions() {
		$dql = "SELECT c.id, c.year, u.username, up.image, c.description FROM AppGuestbookBundle:Champion c
		INNER JOIN AppUserBundle:User u
		WHERE u.id = c.user
		INNER JOIN AppAdminBundle:Upload up
		WHERE up.id = c.image
		WHERE c.status = 1
		ORDER BY c.year DESC";

		$query = $this->getEntityManager()->createQuery($dql);
		$result = $query->execute();

		return $result;
	}	

	public function champions_for_user($id){
		$dql = "SELECT c.year, c.description, u.image
		FROM AppGuestbookBundle:Champion c
		INNER JOIN AppAdminBundle:Upload u
		WHERE u.id = c.image
		WHERE c.user = :id AND c.status = 1
		ORDER BY c.year DESC";

		$query = $this->getEntityManager()->createQuery($dql)
			->SetParameter("id", $id);

		$result = $query->execute();

		if($result)
			return $result;
		else
			return 0;
	}		
}
