<?php

namespace App\GuestbookBundle\Repository;

/**
 * NumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberRepository extends \Doctrine\ORM\EntityRepository
{
	public function get_numbers($user_id, $number){
		$dql = "SELECT n FROM AppGuestbookBundle:Number n
			WHERE n.user = :user OR n.number = :number";

		$query = $this->getEntityManager()->createQuery($dql)
			->SetParameter('user', $user_id)
			->SetParameter('number', $number);

		$result = $query->execute();
		return $result;
	}

	// public function show_numbers(){
	// 	$dql = "SELECT n.id, n.number, n.user, u.username
	// 	FROM AppGuestbookBundle:Number n
	// 	INNER JOIN AppUserBundle:User u
	// 	WHERE u.id = n.user
	// 	ORDER BY n.number ASC";

	// 	$query = $this->getEntityManager()->createQuery($dql);

	// 	$result = $query->execute();

	// 	return $result;
	// }	

	public function show_numbers(){
		$dql = "SELECT n.number, n.user
		FROM AppGuestbookBundle:Number n";

		$query = $this->getEntityManager()->createQuery($dql);

		$result = $query->execute();

		$numbers = [];
		for($i=0;$i<count($result);$i++){
			$user = $result[$i]['user'];
			$number = $result[$i]['number'];
			$numbers[$user] = $number;
		}

		return $numbers;
	}

	public function show_users_numbers(){
		$dql = "SELECT n.id, n.number, n.user, u.username
		FROM AppGuestbookBundle:Number n
		INNER JOIN AppUserBundle:User u
		WHERE u.id = n.user
		ORDER BY n.number ASC
		";

		$query = $this->getEntityManager()->createQuery($dql);

		$result = $query->execute();

		$numbers = [];
		for($i=0;$i<count($result);$i++){
			$id = $result[$i]['id'];
			$user = $result[$i]['user'];
			$username = $result[$i]['username'];
			$number = $result[$i]['number'];
			$numbers[] = ['id' => $id, 'number' => $number, 'user' => $user, 'username' => $username];
		}

		return $numbers;
	}	

	public function number_for_user($id){
		$dql = "SELECT n.number
		FROM AppGuestbookBundle:Number n
		WHERE n.user = :id";

		$query = $this->getEntityManager()->createQuery($dql)
			->SetParameter("id", $id);

		$result = $query->execute();

		if($result)
			return $result[0]['number'];
		else
			return 0;
	}	

}
