<?php

namespace App\VoteBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function get_vote_list($page) {
            $list = $page - 1;
        if($list > 0)
            $list = $list * 10;

        $dql = 'SELECT v.id, v.title, v.status
            FROM AppVoteBundle:Vote v
            WHERE v.status != 0
            ORDER BY v.id DESC';

        $query = $this->getEntityManager()->createQuery($dql)
                ->SetFirstResult($list)
                ->SetMaxResults(10);

        $pagedql = 'SELECT count(v) FROM AppVoteBundle:Vote v WHERE v.status != 0';
        $pagequery = $this->getEntityManager()->createQuery($pagedql);

        $result = $query->execute();
        $rowcountpage = $pagequery->execute();
        $countpage = ceil($rowcountpage[0][1]/10);
        return array($result, $countpage);
    }

	public function show_vote_info($vote) {
		$dql = "SELECT v.id, v.title, v.created, v.completed, v.status, v.user, u.username, v.checked
				FROM AppVoteBundle:Vote v
				INNER JOIN AppUserBundle:User u
				WHERE u.id = v.user
				WHERE v.id = :id";

		$query = $this->getEntityManager()->createQuery($dql)
					  ->SetParameter('id', $vote);

		$result = $query->getSingleResult();

		return $result;
	}	

}