services:
    app.create_tournament:
        class: App\TournamentBundle\Services\createService
        arguments: ['@doctrine.orm.entity_manager']
#    app_tournament.example:
#        class: App\TournamentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
